Added webinterface option for C++ chat client, small Rust config changes
enarx/codex pull request #70
Opened 2022-11-09 18:49 UTC by kieranjazy

Added C++ web interface available by default. Can be disabled by removing --webinterface from Enarx.toml. Uses port 8080. Made small changes to Rust files to fix broken file locations

2022-11-09 18:56 UTC, rjzak commented
A better way to do things might have been to rebase https://github.com/enarx/codex/pull/69 and update.

* So you make your changes.
* `git commit -as` Commit you new changes
* `git rebase -i HEAD~2` Compare last two commits
* Replace the `pick` with `f`
* Save, and git will "fix-up" the commit with the next commit, keeping the history clean.
* `git push -f origin <my branch>` to force push, and if you have an open PR, it'll be automatically updated.

Also, you should probably work in a new branch instead of `main`. This is easy:
* `git checkout main`
* `git pull origin main` to get any changes which might be in your repo
* `git remote add upstream https://github.com/enarx/codex.git` add the main repo as the "upstream"
* `git fetch upstream` get the upstream history
* `git rebase upstream/main` get the latest changes from upstream, add to your `main`
* `git push origin main` freshen up your copy of main
* Make some changes to your code, don't commit yet!
* `git checkout -b <my_new_branch>`
* `git push origin <my_new_branch>`
* Open PR against your branch
* Updates (shown above) will automatically update your PR, don't need to close and make new ones!

If you have any questions, let me know, or ask in the [Enarx chat](https://chat.enarx.dev)

2022-11-09 19:09 UTC, kieranjazy commented
Would it be OK to merge this PR as it is now or should I add it all to a new branch?

2022-11-09 19:20 UTC, rjzak commented
Don't worry about having a new branch this time. Hopefully @rvolosatovs will be able to take a look.

2022-11-09 19:26 UTC, kieranjazy commented
I've it fixed on local, was using your python script to generate the webpage assets but didn't realise it'd break something so I've included it. I'll upload final commit now and solve merge issues

2022-11-09 19:33 UTC, rjzak commented
That's fine for now, but the Nix code should be updated to generate `assets.h` instead of including it.

2022-11-09 20:13 UTC, kieranjazy commented
> That's fine for now, but the Nix code should be updated to generate `assets.h` instead of including it.

Ah ok, I'll look into Nix, haven't used it before

2022-11-11 15:07 UTC, nickvidal commented
Hi @kieranjazy, I tested your PR and it works great. Thanks!

2022-11-11 15:37 UTC, kieranjazy commented
Thanks Nick, just struggling to get Nix to run a Python script for me, still working on it

2022-11-11 16:20 UTC, rvolosatovs commented
> That's fine for now, but the Nix code should be updated to generate `assets.h` instead of including it.

I don't think we need that, at least it should not be a blocker for this PR, this warrants more discussion. Can we file a "goldplating" tech debt issue about it and get this merged?

2022-11-14 11:22 UTC, rvolosatovs requested changes

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/Enarx.toml
> +prot = "tcp"
let's use tls here

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/Enarx.toml
> +port = 8080
Let's use something more unique.
`50000` is already defined as the peer endpoint
How about `50010` for the web interface?

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/c++/README.md
> +Use the --webinterface argument in the Enarx.toml to switch to a web interface, at localhost:8080
Is there a reason not to enable it by default?

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/c++/compile_run.sh
> +$WASI_SDK_PATH/bin/clang++ main.cpp --sysroot $WASI_SDK_PATH/share/wasi-sysroot -o main.wasm &&
I don't think this belongs in the repository, looks like a local development environment tooling

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/c++/main.cpp
> +    bool isWebInterface = false;
I think this should just be enabled by default, we can add functionality to disable it later if we need it

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/c++/process_assets.py
> +ASSETS = ( ("jquery", open("assets/jquery-3.6.0.min.js", "rb").read()), ("chat", open("assets/chat.html", "rb").read()), )
Why add another development dependency for a simple script like this? Can't we use C++ functionality to take care of this directly at compilation time?
Could this be just a simple C++ program, which is run at build time?

2022-11-14 11:22 UTC, rvolosatovs commented on demos/chat-client/c++/process_assets.py
> +#!/usr/bin/env nix-shell
We should not make `nix-shell` a dependency here
```suggestion
#!/usr/bin/env python
```

2022-12-03 22:28 UTC, rvolosatovs commented on demos/chat-client/c++/README.md
> +<<<<<<< HEAD
Looks like an artifact from an unfinished rebase

2022-12-03 22:28 UTC, rvolosatovs commented on demos/chat-client/c++/assets.h
> +unsigned char index_page[1589]= {0x3C,0x21,0x44,0x4F,0x43,0x54,0x59,0x50,0x45,0x20,0x68,0x74,0x6D,0x6C,0x3E,0x0A,0x3C,0x68,0x74,0x6D,0x6C,0x20,0x6C,0x61,0x6E,0x67,0x3D,0x22,0x65,0x6E,0x22,0x3E,0x0A,0
There should be a comment at the top of this file saying that this is auto-generated and pointing to the source.
Could you add the script to the repo as well? We don't have to make it a part of the build pipeline, but there should be a way to reproduce this

2022-12-03 22:34 UTC, rvolosatovs commented on flake.nix
> +          $CXX -Wall -I"./demos/chat-client/c++/assets.h" -pedantic ${demos.chat-client.cpp.src} \
```suggestion
          $CXX -Wall -I"${demos.chat-client.cpp.src}/assets.h" -pedantic ${demos.chat-client.cpp.src}/fibonacci.cpp \
```

Will allow `nix` to access `assets.h` if you set `demos.fibonacci.cpp.src = ./demos/fibonacci/c++;` on L37

2022-12-06 12:25 UTC, rvolosatovs commented on demos/chat-client/Enarx.toml
> +prot = "tcp"
```suggestion
prot = "tls"
```

2022-12-06 12:25 UTC, rvolosatovs commented on demos/chat-client/c++/assets/script.js
> +    var host = "http://localhost:50010"
```suggestion
    var host = "https://localhost:50010"
```

2022-12-06 12:25 UTC, rvolosatovs commented on demos/chat-client/c++/assets/script.js
> +    host = "http://localhost:50010";
unused?

2022-12-06 12:26 UTC, rvolosatovs commented on demos/chat-client/c++/assets/script.js
> +function createChatBot() {
There should not be a bot

2022-12-09 20:39 UTC, rvolosatovs commented
@kieranjazy I believe the outdated `wasi-libc` issue is now solved, but the code still fails to compile with:
```
chat-client-wasm32-unknown-wasi> /nix/store/fxasr4jvncasd20wkisj6wf78gyww84y-c++/main.cpp:17:21: warning: unused variable 'HTTP_NOT_FOUND' [-Wunused-const-variable]
chat-client-wasm32-unknown-wasi> const unsigned char HTTP_NOT_FOUND[14] = "HTTP/1.0 404\n";
chat-client-wasm32-unknown-wasi>                     ^
chat-client-wasm32-unknown-wasi> /nix/store/fxasr4jvncasd20wkisj6wf78gyww84y-c++/main.cpp:19:21: warning: unused variable 'CONTENT_TYPE_PLAIN' [-Wunused-const-variable]
chat-client-wasm32-unknown-wasi> const unsigned char CONTENT_TYPE_PLAIN[27] = "Content-Type: text/plain\n\n";
chat-client-wasm32-unknown-wasi>                     ^
chat-client-wasm32-unknown-wasi> 2 warnings generated.
chat-client-wasm32-unknown-wasi> /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 3: -o: command not found
```

2022-12-09 20:41 UTC, rvolosatovs requested changes

2022-12-09 20:41 UTC, rvolosatovs commented on flake.nix
> +          $CXX -Wall -I"${demos.chat-client.cpp.src}/assets.h" -pedantic ${demos.chat-client.cpp.src}/main.cpp
```suggestion
          $CXX -Wall -I"${demos.chat-client.cpp.src}/assets.h" -pedantic ${demos.chat-client.cpp.src}/main.cpp \
```

2022-12-09 20:41 UTC, rvolosatovs commented on demos/chat-server/rust/.cargo/config
> +runner = ["enarx", "run", "--wasmcfgfile", "../Enarx.toml"]
Can we avoid this diff?
Is it possible for you to extract this into a separate PR?

2022-12-09 20:41 UTC, rvolosatovs commented on demos/chat-server/rust/Cargo.lock
> +[[package]]
Same as above

2022-12-14 17:11 UTC, rvolosatovs approved these changes

2022-12-14 17:17 UTC, merged