feat(chat-client): add Web UI
enarx/codex pull request #73
Opened 2022-11-18 19:34 UTC by nickvidal

Add Web UI for chat clients.

Waiting for PR #70 to get merged before making connections from Rust, C++, and C chat clients.

Signed-off-by: Nick Vidal <nick@profian.com>

2022-11-18 19:58 UTC, rvolosatovs requested changes
Let's move
`/demos/chat-client/chat-web-ui` -> `/demos/chat-client/web-ui`

There should not be a pop-up, rather once opened, the maximized chat window should immediately appear without having to click any buttons.

I only see functionality to send messages, how are messages ever fetched from the server?
In any case, this UI should rely on a WebSocket to send and receive messages https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

2022-11-18 19:58 UTC, rvolosatovs commented on demos/chat-client/chat-web-ui/script.js
> +    var host = "http://localhost:8080"
This should:
1. Use something more unique. I suggested port `50010` in #69 
2. Use `https`

2022-11-18 19:58 UTC, rvolosatovs commented on demos/chat-client/chat-web-ui/script.js
> +}
There should be no bots, if you want to initialize elements with some data, just do that directly in initialization routine

2022-11-18 19:58 UTC, rvolosatovs commented on demos/chat-client/chat-web-ui/script.js
> +    host = "http://localhost:8080";
unused?

2022-11-21 14:19 UTC, nickvidal commented
The Chat window is now fully expanded. Maybe one of the students can work on the WebSocket?

2022-11-21 15:02 UTC, rvolosatovs requested changes
@nickvidal this still does not fit the purpose.

We should be printing lines of text to a blank page and be able to send lines of text.
There is no concept of a "user" or anything like that in the protocol

I would expect to see a white page with black text on top, printed directly from the server and a small form below to send a line.

There cannot be a bot here.

Why is not just all the text printed on the page itself? What's the purpose of the "box"?

2022-11-21 15:12 UTC, rvolosatovs commented
I haven't seen @kieranjazy's UI, but I have a feeling that that work was much better suited for what we're building. Where can I find that?

2022-11-21 15:37 UTC, rvolosatovs commented
These messages are *not* meant for humans.
We may come up with something humans can interact with, but that will not be uncensored text.

Note that even if we wanted to build a generic chat application for humans, we simply could not publish an anonymous, uncensored chat on https://try.enarx.dev

2022-11-22 03:58 UTC, rvolosatovs approved these changes
Let's handle the rest in a follow-up

2022-11-22 03:58 UTC, merged